title: Animsition
description: A simple and easy jQuery plugin for CSS animated page transitions.
url: http://git.blivesta.com/animsition
repo_url: https://github.com/blivesta/animsition
author: blivesta
author_url: http://blivesta.com
twitter: blivesta
tag: jquery,css3,animsition
git_fork_btn: http://ghbtns.com/github-btn.html?user=blivesta&amp;repo=animsition&amp;type=fork&amp;count=true
git_star_btn: http://ghbtns.com/github-btn.html?user=blivesta&amp;repo=animsition&amp;type=watch&amp;count=true
git_follow_btn: http://ghbtns.com/github-btn.html?user=blivesta&type=follow&count=false
