title: Animsition
pkg_name: animsition
url: http://git.blivesta.com/animsition/
description: A simple and easy jQuery plugin for CSS animated page transitions.
tag: jquery, css3, animsition, transition
author: blivesta
author_url: http://blivesta.com/
maintainer: ungki
maintainer_url: https://github.com/ungki
